version: '3.1'

services:

  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
#    volumes:
#      - ./src/:/app/src/
  db:
    image: postgres
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres